package com.example.chatapplication2.activitytest

import android.os.Bundle
import android.view.View
import android.widget.Toast
import androidx.activity.viewModels
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.Observer
import com.example.chatapplication2.databinding.ActivityBookTagBinding
import com.example.chatapplication2.model.BookTag
import com.example.chatapplication2.viewmodel.BookTagViewModel

class BookTagActivity : AppCompatActivity() {

    private val bookTagViewModel: BookTagViewModel by viewModels()
    private lateinit var binding: ActivityBookTagBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityBookTagBinding.inflate(layoutInflater)
        setContentView(binding.root)

        // Observe book tags LiveData
        bookTagViewModel.bookTagsLiveData.observe(this, Observer { bookTags ->
            // Handle displaying book tags in the UI (e.g., in a RecyclerView)
            // Example:
            // bookTagAdapter.submitList(bookTags)
            Toast.makeText(this, bookTags.toString(), Toast.LENGTH_SHORT).show()
        })

        // Observe error messages
        bookTagViewModel.errorLiveData.observe(this, Observer { errorMessage ->
            if (!errorMessage.isNullOrEmpty()) {
                Toast.makeText(this, errorMessage, Toast.LENGTH_SHORT).show()
            }
        })

        // Add Book Tag button click listener
        binding.btnAddBookTag.setOnClickListener {
            val newBookTag = BookTag(
                btid = "", // Will be generated by Firestore
                tagId = binding.etTagId.text.toString(),
                bookId = binding.etBookId.text.toString()
            )
            bookTagViewModel.addBookTag(newBookTag)
        }

        // Get Book Tags button click listener
        binding.btnGetBookTags.setOnClickListener {
            bookTagViewModel.getBookTags()
        }
    }
}
