package com.example.chatapplication2.activitytest

import androidx.activity.enableEdgeToEdge
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import com.example.chatapplication2.R

import android.os.Bundle
import android.widget.Toast
import androidx.activity.viewModels
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.Observer
import com.example.chatapplication2.databinding.ActivityGroupEntryRequestBinding
import com.example.chatapplication2.model.GroupEntryRequest
import com.example.chatapplication2.viewmodel.GroupEntryRequestViewModel

class GroupEntryRequestActivity : AppCompatActivity() {

    private val groupEntryRequestViewModel: GroupEntryRequestViewModel by viewModels()
    private lateinit var binding: ActivityGroupEntryRequestBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityGroupEntryRequestBinding.inflate(layoutInflater)
        setContentView(binding.root)

        // Observe group entry requests LiveData
        groupEntryRequestViewModel.groupEntryRequestsLiveData.observe(this, Observer { groupEntryRequests ->
            // Handle displaying group entry requests in the UI (e.g., in a RecyclerView)
            // Example:
            // groupEntryRequestAdapter.submitList(groupEntryRequests)
        })

        // Observe error messages
        groupEntryRequestViewModel.errorLiveData.observe(this, Observer { errorMessage ->
            if (!errorMessage.isNullOrEmpty()) {
                Toast.makeText(this, errorMessage, Toast.LENGTH_SHORT).show()
            }
        })

        // Add Group Entry Request button click listener
        binding.btnAddGroupEntryRequest.setOnClickListener {
            val newGroupEntryRequest = GroupEntryRequest(
                gerid = "", // ID will be generated by Firestore
                userId = binding.etUserId.text.toString(),
                groupId = binding.etGroupId.text.toString(),
                requestComment = binding.etRequestComment.text.toString()
            )
            groupEntryRequestViewModel.addGroupEntryRequest(newGroupEntryRequest)
        }

        // Get Group Entry Requests button click listener
        binding.btnGetGroupEntryRequests.setOnClickListener {
            groupEntryRequestViewModel.getGroupEntryRequests()
        }

        // Update Group Entry Request button click listener
        binding.btnUpdateGroupEntryRequest.setOnClickListener {
            val requestId = binding.etRequestId.text.toString()
            val updatedGroupEntryRequest = GroupEntryRequest(
                gerid = requestId,
                userId = binding.etUserId.text.toString(),
                groupId = binding.etGroupId.text.toString(),
                requestComment = binding.etRequestComment.text.toString()
            )
            groupEntryRequestViewModel.updateGroupEntryRequest(requestId, updatedGroupEntryRequest)
        }

        // Delete Group Entry Request button click listener
        binding.btnDeleteGroupEntryRequest.setOnClickListener {
            val requestId = binding.etRequestId.text.toString()
            groupEntryRequestViewModel.deleteGroupEntryRequest(requestId)
        }
    }
}
