package com.example.chatapplication2.activitytest

import android.os.Bundle
import android.widget.Toast
import androidx.activity.viewModels
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.Observer
import com.example.chatapplication2.databinding.ActivityGroupChatBinding
import com.example.chatapplication2.model.GroupChat
import com.example.chatapplication2.viewmodel.GroupChatViewModel

class GroupChatActivity : AppCompatActivity() {

    private val groupChatViewModel: GroupChatViewModel by viewModels()
    private lateinit var binding: ActivityGroupChatBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityGroupChatBinding.inflate(layoutInflater)
        setContentView(binding.root)

        // Observe group chats LiveData
        groupChatViewModel.groupChatsLiveData.observe(this, Observer { groupChats ->
            // Handle displaying group chats in the UI (e.g., in a RecyclerView)
            // Example:
            // groupChatAdapter.submitList(groupChats)
        })

        // Observe error messages
        groupChatViewModel.errorLiveData.observe(this, Observer { errorMessage ->
            if (!errorMessage.isNullOrEmpty()) {
                Toast.makeText(this, errorMessage, Toast.LENGTH_SHORT).show()
            }
        })

        // Add Group Chat button click listener
        binding.btnAddGroupChat.setOnClickListener {
            val newGroupChat = GroupChat(
                gcid = "", // ID will be generated by Firestore
                theme = binding.etTheme.text.toString()
            )
            groupChatViewModel.addGroupChat(newGroupChat)
        }

        // Get Group Chats button click listener
        binding.btnGetGroupChats.setOnClickListener {
            groupChatViewModel.getGroupChats()
        }

        // Update Group Chat button click listener
        binding.btnUpdateGroupChat.setOnClickListener {
            val groupId = binding.etGroupChatId.text.toString()
            val updatedGroupChat = GroupChat(
                gcid = groupId,
                theme = binding.etTheme.text.toString()
            )
            groupChatViewModel.updateGroupChat(groupId, updatedGroupChat)
        }

        // Delete Group Chat button click listener
        binding.btnDeleteGroupChat.setOnClickListener {
            val groupId = binding.etGroupChatId.text.toString()
            groupChatViewModel.deleteGroupChat(groupId)
        }
    }
}
